import Button from 'material-ui/Button'
import { withStyles } from 'material-ui/styles'
import { shape, string } from 'prop-types'
import AppPage from '../../templates/app-page'
import { optOut } from '../../../integrations/analytics'

const styles = theme => {
  return {
    content: {
      padding: theme.spacing.unit,
      maxWidth: '960px',
      margin: '0 auto',
    },
  }
}

const Privacy = ({ classes }) => (
  <AppPage title='Your Privacy'>
    <div className={classes.content}>
      <p>This website uses Google Analytics, a web analysis service of Google Inc, (1600 Amphitheatre Parkway Mountain View, CA 94043, USA; &quot;Google&quot;). The use includes the &quot;Universal Analytics&quot; operating mode. This facilitates the assignment of data, sessions and interactions across several devices to a pseudonymous user ID and thus the analysis of a user&apos;s activities across devices.</p>
      <p>Google Analytics uses &quot;cookies&quot;, which are text files placed on your computer, to allow the website operator to analyze how users use the site. The information generated by the cookie about your use of this website is usually transferred to a Google server in the USA and stored there. However, if IP anonymisation is activated on this website, Google will reduce your IP address within Member States of the European Union or in other states party to the Agreement on the European Economic Area beforehand. Only in exceptional cases will the full IP address be transmitted to a Google server in the USA and shortened there. The IP address transmitted by your browser in the context of Google Analytics is not merged with other Google data. On behalf of the operator of this website, Google will use this information to evaluate your use of the website, to compile reports on website activity and to provide the website operator with other services related to website and Internet use. Our legitimate interest in data processing also lies in these purposes. The legal basis for the use of Google Analytics is § 15 para. 3 TMG and Art. 6 para. 1 lit. f GDPR. Sessions and campaigns are terminated after a certain period of time. By default, sessions are closed after 30 minutes without activity and campaigns after six months. The time limit for campaigns may not exceed two years. For more information on terms of use and data protection, please visit <a href='https://www.google.com/analytics/terms/gb.html' target='_blank' rel='noopener noreferrer'>https://www.google.com/analytics/terms/gb.html</a> or <a href='https://policies.google.com/?hl=en' target='_blank' rel='noopener noreferrer'>https://policies.google.com/?hl=en</a>.</p>
      <p>You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. You can also prevent Google from collecting the data generated by the cookie and relating to your use of the website (including your IP address) and from processing this data by Google by downloading and installing the <a href='https://tools.google.com/dlpage/gaoptout?hl=en'>Browser Add-on</a>. Opt-out cookies prevent the future collection of your data when you visit this website. To prevent Universal Analytics from collecting data across several devices, you must opt-out on all systems used. </p>
      <p>
        If you click here, the opt-out cookie will be set: <Button onClick={optOut} size='large' variant='raised' color='primary'>Disable Google Analytics</Button>
      </p>
    </div>
  </AppPage>
)

Privacy.propTypes = {
  classes: shape({
    content: string.isRequired,
  }).isRequired,
}

export default withStyles(styles)(Privacy)
