# SmashPic Travis CI control file
# Node version is read from .nvmrc
---
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
env:
  global:
    - CI_COMMIT=$TRAVIS_COMMIT
    - CI_TAG=$TRAVIS_TAG
    # Sentry DSN
    - secure: XASO5TGDAfqW5QXRmglBC2LAi85P7LApfuW1l7duT/ODjsE0HXe5Vhm1wQd3xg5QDMFz0ssDInEwCuHKBnqD8tC9QkCQkUo5UQLYtbkP3YwpSaKaZSjbWYuzyCzL5pEC7bgPotjra65DBsbQjnDnnqkUOhFxUiLJB0MaoOlotF8gfPFAWbMPrINf43+PtWwA9dduV1+/zUH5rsxZQz35h5OKy/qXGyUUDjQog6IJUaavwKyKlHwHccSiZboFLzCgT8YuJakJgKHuCmVFvaUymYQ3fL3jHY/NxVoBfUGh3gsTkwx9lfK/N27JjFaHwca300UUgAkacu0o3pjrI1QwUE6fZD95EmHmMqWWAEfgp8Hjr4kLPj66U//NIyMmCzxtEF/tCJY1hGiIj1StQWYVjdoVIdOWq8r0j+miMG6UKkjPOoDMdAt2aSHS0y71F46OMftME3AdlXFJFjTNiZwNsSFkhYzkubYpfa9NiShAXHHmlBZ3kt2o0oHvnyaL7t4opS8SNBcZJtu9+6NELdaWzAEGEkg5VkOdMBz1NVLrMDqtjNyWZaHXiOfSeprB2s0hfbSObR+R1R+ZQcRH/L2L9IM203xpJ4YABBs93e0EHv+bJn2a5flIKe88kD04D8Q4VVM0+O9WDpHr+msacq4ORXCt11RRgm32l5OK4pGKEEY=
    # Google Analytics
    - secure: s1STqK/rN3b9Dcryi9qmIkqhVYlGSZ94UkwMRJnC8frpUppAPweVe5ZsOhEYhJ8a485RWQWs4DRbL3uqNpaSeGQZrpveUuu3vqvQ12w7qab9ltYZeZFeRDNMzIbPEdAUzSWifBe4jBig1wzFpgPeVGu3su5BNyBe8m6NSEeAI/Kr21aq1XANdlUnET0dPD9B9Tg5AF+GuJ8nNSRiHKTR9s+2gO+fGFV8yNC0mTxaytb+tw7RlTyFrq7aMIFzvVXtxc8iQrvHNmqkGZqCnRzl2yVitj4ba0kabKHlcRD10CqhzQTB+kzMUoGYeCmK83hYAqmF8NIRgeN6o9QXplLQViuuuBzuGbHyN45+e2VlvnBlbNdchEg9mTlQVeYWtJhNcxGqvOs7x9uKtY93268c06GAe5Ad7A6peAic2ml0WZH0tGpG0GbUE57Ry1cT7uG+YmnzyhI5mI2o+BpBPsTSZ8tJo5UQWECExMCCfMf6xyX3/XS1Pay2rm18Bhkvuil9NkpMKTqKEB2lxuArNXzTFQfhBuNAXkxHULHGHOLcjqcme3Gt3rzpyoVtW21mdOuNjzVNuMvsAw7BBGF37jtjNMvRFTz81xvT+Yvo84vSyXWlXkuzorNtJQnrYkj+sfalSrI0ZZhEQIRslhfFak05Dko2lvOELWszTU2u+hjXf7Q=
script:
  - npm run lint
  - NODE_ENV=test npm test
  - NODE_ENV=production npm run build
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure:   "ZkLAnV4hzIMJcjBIrs+1ZDz4cWApJmM8CuL1N26hZGFkIMATV6ioiYJ98D1Q27srZUyw923uCjKUwIdAL0b33jyXQ13ui3U12oGOm9JJzPAH595okAxJL8wK85w+6oRthwzNxTwWztddjCIGunWx8sbXLyPwwnOIgcmrJRymcVVHL4R9Kf7DRQLc6Xm6elpgi0mcJ/QMqn09Gy+VVgH91EWHAReMXwehrlKKhM5aGc7Rn5ORPX+bOunKMe9XqKKb0zMtGWBnkdf5v/+Jl8YdaBxuKPQ3h8II61Y6E78v1M3SfgLqYLFSFBKeg+AbDlxvcwq3sGcokqC8KQ6drR0/s/SR5J9iUDmUz0dOs9QJFVO5ujchtSbRmMxprYpvXKz5IJPeZXA8OpyT+qtPe9rhHAPJWePGBIpekyzCWhXb89BO9jkZsqUCiK/wofvtTMC7iY2dTfZ5J5HBkA8h6OoxkIJ0EVz5GXDp2gL1WJX9Yi225Q6  my79Pb9yeC1DsRccAjj3iDtsIr1zFdYVo4sz/hCFGbMhh4ruO/wdK44pQ0ZrEOnw/acdJLGeYeBQBA3q8qHczU836WC/eVFvpwmDgJKLwuqZGW40MIM69tnGtFtQ7xaAZSYtj+PGqEHNQeo47KsqV3FN4nGcMqtS+euIzjcowMMEXPHDD8b+eTNSjb9w="
    project: 'smashpic-canary'
    message: $TRAVIS_COMMIT
    on:
      branch: master
